import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import { Shippori_Mincho } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pure Aesthetics",
  description: "Generated by create next app",
};

const shippori = Shippori_Mincho({
  variable: "--font-shippori",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${shippori.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
